### ISSUE TITLE
Play random video files in 6-panel window

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/VideoWatcher#1]
Core feature is to randomly select videos (from local storage in v1.0) and play them in 6 panels filling the screen of an iOS device.

**Comment by tedbarnett** [comment]
Looks like only 5 of the panels are working. The bottom left one (on my iPhone) is blank always.

**Comment by tedbarnett** [comment]
![image](https://github.com/tedbarnett/VideoWatcher/assets/694013/36e3630d-f7e8-4733-a45a-dd6888f1d676)

**Comment by bhautikpatoliya004** [comment]
@tedbarnett Do you still get this issue? Currently, I added a label on a panel with the video name which is not able play.

**Comment by tedbarnett** [comment]
Not getting that issue now and I did see the error message.  That must be what happened before.  We will have to figure out how to handle un-playable videos later (add to a list?) but your solution works!  I will close this issue.
