### ISSUE TITLE
Enable full-screen option

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/VideoWatcher#10]
If the full-screen option is selected from the pop-up menu:
* Zoom that video panel out to fill the screen (so that the video fits both height and width)
* Otherwise should operate as a video in the panel form does (pop-up menu available, etc.)
* Will later add scrubbing and favorite clip selection to this mode...

**Comment by bhautikpatoliya004** [comment]
@tedbarnett Do you have any screen design in mind for full-screen mode? And what options will be there in full-screen mode?

**Comment by tedbarnett** [comment]
In full-screen mode, we want the user to be able to play/pause the video, mute/unmute audio, and select favorite clips.  For now, let's assume we can only create one favorite clip per video (to keep things simple and see how it works).  Eventually, we need a way to be able to create several favorite clips from a single video (since some videos are very long).  

For Selecting Favorite clips, I'd like to copy Apple's own video editing interface (i.e. when you open a video file in Apple Photos on iPhone or iPad).  See screenshot below.

**Comment by bhautikpatoliya004** [comment]
Apple does not provide direct public APIs to integrate the built-in video editor of the Photos app into our own iOS app. The video editor you're referring to is a part of the Photos app and is not available as a separate component that can be embedded into third-party apps. If we want to provide video editing capabilities similar to the Photos app within our own app, we would need to implement our own video editing interface using the AVFoundation framework or consider using third-party libraries that offer video editing functionality. So, for now, I’ve implemented one screen that provides clip creation from full-screen mode. Today I’ve implemented the UI of the screen and clicked on "Save clip" button asking for the clip name. I will continue working on it tomorrow.

Can you please let me know, the created clip will also display on 6 Panels as we pick random videos from our local database?  Or this clip will only display on the Favorite screen?

**Comment by tedbarnett** [comment]
We will need a way for users to see that a particular video has multiple clips (hearts). My thought is that if there are any clips inside the video that the heart icon becomes a black or pink heart. Or looks like a little stack of hearts.

**Comment by bhautikpatoliya004** [comment]
@tedbarnett Where do I need to show the heart icon?

**Comment by tedbarnett** [comment]
If a video has "clips" inside of it, just show a different heart icon on the main panel screen.  For now: a heart with a white interior?  If the heart is for the entire video, a red heart.
