### ISSUE TITLE
Use new ClipHeart icon

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/VideoWatcher#11]
Can we make this image into the icon for this app (with a transparent background maybe)?

![image](https://github.com/tedbarnett/VideoWatcher/assets/694013/1d16570d-6fb6-403e-acaa-355b97e7ed5d)

**Comment by bhautikpatoliya004** [comment]
@tedbarnett Yes, we can use the above icon as app icon. However, Apple's guidelines require app icons to have a solid background color. Transparent app icons are not allowed.

**Comment by tedbarnett** [comment]
Good point. For now it could have a black background.
