### ISSUE TITLE
Import from Dropbox

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/VideoWatcher#16]
My 1TB of videos is stored on Dropbox. I should be able to specify a Dropbox folder to import.

**Comment by bhautikpatoliya004** [comment]
@tedbarnett I’ve done some R&D on the Dropbox file browser after user authentication, but there is no pre-built UI provided by SwiftyDropboxSDK(Official Dropbox SDK for iOS). So, we need to develop our own Dropbox file browser to import videos from Dropbox. And it will take more time. So, I’ve skipped “Import from Dropbox #16” for now and implement it later.

**Comment by bhautikpatoliya004** [comment]
@tedbarnett We have to provide a path to download a file/folder of Dropbox if we want to import videos from it. In actuality, the file will be downloaded from Dropbox and it will take time(Based on network).
 If users want to import the local Dropbox's downloaded file from the Apple Files > Dropbox then they can do it manually, like we added the option "Import video from Files" app.
And for shared folder of Dropbox, maybe it will based on permissions of the logged in user.

**Comment by tedbarnett** [comment]
I'm able to authenticate to Dropbox okay, but I then just see an empty screen.  Ideally I would see a list of the folders in  my Dropbox and I could navigate to the one that has my videos.

**Comment by tedbarnett** [comment]
![image](https://github.com/tedbarnett/VideoWatcher/assets/694013/b30b3e6a-6b55-41d2-8ff1-6c385a5acb80)

**Comment by tedbarnett** [comment]
Ideally, once logged into Dropbox, i would see the top level directory of my Dropbox folder (see below from Dropbox mobile app).  I could then click folders to navigate into them (and a back or up button to navigate out of a folder).  Since we are filtering to only show video files (and folders I presume!), can we add a message at the bottom reading ("Choose video files to add (.mov or .m4v only")

**Comment by bhautikpatoliya004** [comment]
Can you please wait for sometime? In my account, firstly showing no video label and then after 3-5 seconds the folder appear

**Comment by tedbarnett** [comment]
Okay.  Trying again...

**Comment by tedbarnett** [comment]
Logged out and in again (using your account).  Saw screens of folders and videos, but if I tap them, nothing happens (blinks briefly is all).

**Comment by tedbarnett** [comment]
Screen looks fine...

![image](https://github.com/tedbarnett/VideoWatcher/assets/694013/f8a25794-a9c9-43ef-b68b-cbd1ea236820)

**Comment by tedbarnett** [comment]
Already authorized 1
[{
    id = "id:9CZbtTCPnjsAAAAAAAAABg";
    name = VideoWatcher;
    "path_display" = "/VideoWatcher";
    "path_lower" = "/videowatcher";
}, {
    id = "id:9CZbtTCPnjsAAAAAAAAAEg";
    name = Android;
    "path_display" = "/Android";
    "path_lower" = "/android";
    "shared_folder_id" = 4453595089;
    "sharing_info" =     {
        "no_access" = 0;
        "read_only" = 0;
        "shared_folder_id" = 4453595089;
        "traverse_only" = 0;
    };
}, {
    "client_modified" = "2023-08-24T07:00:09Z";
    "content_hash" = ff9de9e76af4c9d1bd688b81df399df2558151c9a344806c04687e1b9b11e589;
    id = "id:9CZbtTCPnjsAAAAAAAAADw";
    "is_downloadable" = 1;
    name = "Simulator Screen Recording - iPhone 14 Pro - 2023-07-27 at 11.08.52.mp4";
    "path_display" = "/Simulator Screen Recording - iPhone 14 Pro - 2023-07-27 at 11.08.52.mp4";
    "path_lower" = "/simulator screen recording - iphone 14 pro - 2023-07-27 at 11.08.52.mp4";
    rev = 603a5c75fe5d46c03bc73;
    "server_modified" = "2023-08-24T07:00:09Z";
    size = 2524212;
}]
Selected path: /VideoWatcher
[{
    id = "id:9CZbtTCPnjsAAAAAAAAACQ";
    name = "Test Bhautik";
    "path_display" = "/VideoWatcher/Test Bhautik";
    "path_lower" = "/videowatcher/test bhautik";
}, {
    id = "id:9CZbtTCPnjsAAAAAAAAADQ";
    name = Photos2;
    "path_display" = "/VideoWatcher/Photos2";
    "path_lower" = "/videowatcher/photos2";
}, {
    "client_modified" = "2023-08-07T10:53:23Z";
    "content_hash" = a049abaaa43a44180caf750f4aec85e0989901c1ba33b6a89b51ef8a7ac5039b;
    id = "id:9CZbtTCPnjsAAAAAAAAABw";
    "is_downloadable" = 1;
    name = "149068 (Original).mp4";
    "path_display" = "/VideoWatcher/149068 (Original).mp4";
    "path_lower" = "/videowatcher/149068 (original).mp4";
    rev = 602530e2778496c03bc73;
    "server_modified" = "2023-08-07T10:53:23Z";
    size = 3399231;
}, {
    "client_modified" = "2023-08-07T10:54:12Z";
    "content_hash" = ab7cfdc1f476ecaf9202116af7db3b73fb79c6965095595185128b8236b8c596;
    id = "id:9CZbtTCPnjsAAAAAAAAACA";
    "is_downloadable" = 1;
    name = "RPReplay_Final1691223752.MP4";
    "path_display" = "/VideoWatcher/RPReplay_Final1691223752.MP4";
    "path_lower" = "/videowatcher/rpreplay_final1691223752.mp4";
    rev = 602531112fb616c03bc73;
    "server_modified" = "2023-08-07T10:54:12Z";
    size = 37890625;
}]
We can download it
We can download it

**Comment by tedbarnett** [comment]
You nailed it!
