### ISSUE TITLE
Manage videos menu

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/VideoWatcher#20]
Change "Import more videos" to "Manage videos"

When selected, opens a dialog box with:
- A scrolling list of favorite clips that you can delete or rename
- a "+" button that opens an import dialog from Apple Photos, Google Drive, and Dropbox

**Comment by bhautikpatoliya004** [comment]
@tedbarnett Added swipe to delete or rename.

**Comment by tedbarnett** [comment]
Nice!
