### ISSUE TITLE
Move mute control to a top-left icon on each panel

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/VideoWatcher#34]
Let's make the force-push only have one option: "Delete".  Eliminate the mute/unmute menu option there.  Instead...
- Show the same mute/unmute icon as used in the full-screen view.  Place it in the top-left of each panel.

**Comment by tedbarnett** [comment]
Can we also make the force-push work when in the full-screen mode (so a user can choose to delete the video while watching it in full-screen mode)?

**Comment by bhautikpatoliya004** [comment]
@tedbarnett Yes, we can make force-push in full-screen mode too but we have to decide a specific place for force-push. Could you please let me know, on the push what to display the force-push menu?
