### ISSUE TITLE
Dropbox file list improvements

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/VideoWatcher#39]
Any way to:
- list the Dropbox files alphabetically?  The list seems randomly sorted. 
- allow the file name text to "wrap" (or even continue off to the right where I can scroll over to read it all). My names are so long I cannot read them when truncated. 

![image](https://github.com/tedbarnett/VideoWatcher/assets/694013/62408258-e170-43c7-8069-cf22b5e681b4)

**Comment by tedbarnett** [comment]
Yay!

**Comment by bhautikpatoliya004** [comment]
@tedbarnett In Dropbox, they are not returning all files (For example, 4000 videos) at once, they are sending 500 files first time then we need to check their API response, hasMore records? If has more records then we have to call another API to get the next 500 records. So, I've implemented it now.
Regarding sorting alphabetically, I'm sorting alphabetically like, the first 500 sorting alphabetically and then another 500 (500+500 = 1000), sorting alphabetically, and so on.
