### ISSUE TITLE
iPad intro screen

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/VideoWatcher#42]
Just installed the app on my iPad Pro. It looks awesome!

One issue: the intro text does not include the list of platforms (Apple, Dropbox, Google Drive). The text is truncated?  Saw this in landscape mode on an iPad Pro.

**Comment by bhautikpatoliya004** [comment]
@tedbarnett Can you please send a screenshot? I've tested it on a iPad Pro (12 9-inch) simulator and it's showing the whole label.

![Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2023-09-04 at 17 45 18](https://github.com/tedbarnett/VideoWatcher/assets/114083934/a1eae783-9357-4a62-95c2-ac0885bb4b34)

**Comment by tedbarnett** [comment]
![image](https://github.com/tedbarnett/VideoWatcher/assets/694013/4957b900-9636-4f7a-8a14-fe0284124714)

![image](https://github.com/tedbarnett/VideoWatcher/assets/694013/668daa29-e23c-460f-af7e-93f5f43f2df5)

**Comment by tedbarnett** [comment]
Landscape mode: 
![image](https://github.com/tedbarnett/VideoWatcher/assets/694013/b8e23a18-a3c2-4361-b9c1-b3f369169006)
