### ISSUE TITLE
Wrong video opens in full screen

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/VideoWatcher#44]
On my iPad in landscape mode, if I tapped the top left video, a different video opened when in full screen mode. When I closed that window and returned to the main screen, the original video was playing.

**Comment by tedbarnett** [comment]
https://github.com/tedbarnett/VideoWatcher/assets/694013/617407fd-ab86-4351-bc8b-0a9f8cb4c98c

**Comment by bhautikpatoliya004** [comment]
@tedbarnett I've tested it but didn't get the issues you showed here. But as you got this issue then this issue must exist. So do you have any specific steps to reproduce this issue? For now, I added one label at the top to identify the panel number and video name in the full-screen mode.

**Comment by tedbarnett** [comment]
I'll keep trying...
