### ISSUE TITLE
Export favorites list

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/VideoWatcher#6]
Let's make sure we save the favorite clips data in a format that can be used elsewhere (or exported).  If someone uses this app for many hours to hand-create clips that matter, we don't want to lose their data.  Maybe we at least save a CSV file to their phone.  Something like this (which I had made for myself):

https://docs.google.com/spreadsheets/d/1wddsIQYyVbqpyuEyBwMcJnervYv4P5qRkFPxA8SjF6o/edit?usp=sharing

**Comment by tedbarnett** [comment]
Just granted permission!

**Comment by bhautikpatoliya004** [comment]
@tedbarnett Thanks.
It seems that there are a 4 columns inside CSV file. Can you please explain 2nd and 3rd column?

**Comment by bhautikpatoliya004** [comment]
@tedbarnett It seems that there are a 4 columns inside CSV file. Can you please explain 2nd and 3rd column?

**Comment by tedbarnett** [comment]
I added a title row to the CSV file above.  The columns are:
- Video file name (source)
- Start position of clip (in seconds)
- Title for clip
- Date of video (read from original file I think - maybe ignore for now)

**Comment by tedbarnett** [comment]
Where is this file saved?

**Comment by bhautikpatoliya004** [comment]
@tedbarnett Currently, I’ve open the share sheet with the created file. Didn’t saved anywhere. Do we need to save it? And where?

**Comment by tedbarnett** [comment]
Could we add a setting to "export favorites list" that lets users send the csv to themselves?

**Comment by bhautikpatoliya004** [comment]
@tedbarnett Yes we can add. Do I need to add it as a menu option main panel screen?

**Comment by tedbarnett** [comment]
Yes.  Click on settings, a settings dialog appears. Only one item on it (so far). A share icon with this label:

Export favorite clips CSV
