### ISSUE TITLE
Enable mute on/off

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/VideoWatcher#7]
By default, all videos are playing at zero volume (i.e. muted).  If the user selects (via the pop-up menu) to "unmute" a particular video, then...
* that video's volume should be turned on (set to default volume level)
* a red speaker icon should appear in the top left of that video panel (which, if tapped, turns the volume back to mute).  Use same speaker icon as in Boswell
* Behavior should be the same if in full-screen mode for a video

**Comment by bhautikpatoliya004** [comment]
![Mute:Unmute](https://github.com/tedbarnett/VideoWatcher/assets/114083934/57ce75ba-c6ce-4a89-acb3-6fa8d181cf44)

This is done, Please check it.
