### ISSUE TITLE
Enable skip forward/back (next/previous)

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/VideoWatcher#8]
* change the name of these menu items to "next video" and "previous video" (not skip forward and back)
* when "next video" is selected, the video in that panel should change to another random video (but need to keep track of history so that "previous" will work below)
* If there is no "previous video" (since the user has never chosen "next video" on that panel before), grey out the "previous video" option
* when "previous video" is available and is selected: in that panel, skip back to the previous video.   User can keep doing this until they get back to the first video that was played in that panel.

**Comment by tedbarnett** [comment]
Correct: when the videos first load the "previous video" menu item should be grayed out for each of them.  Once they choose "Next video" for that panel, it will switch to that video and enable the "previous video" menu item.  Make sense?

**Comment by bhautikpatoliya004** [comment]
@tedbarnett Each time when we open the app, I'm loading random videos for all 6 panels from the local video database. So, the "previous video" of the particular panel should be wiped out when we close the app? I think it should wipe out the previous videos when we close. Make sense?
